### PR TITLE
Make sure VideoAttachment always have the play icon by default.

### LINKED ISSUE #813: Video Attachment should alway have by default an play icon overlay image
### Expected behavior

- If the overlayImage is removed from a VideoAttachment by default the system should restore the play icon overlay

### Actual behavior

- If the system set the image to nil the play overlay goes away and needs to be restored manually

### Steps to reproduce the behavior

- Activate the media upload error mode
- Add a new video on the demo
- Wait for the error, 
- Tap on the video
- Tap somewhere else

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #813 

To test:
 - Start the empty demo app
 - Add a new media video object
 - Tap on it
 - Tap on another media
 - See that the icon on the video resets to the play button.
 - Activate the error mode by switch the `errorMode` variable to true on the `EditorDemoController`
 - Repeat the steps above.

### CODE REVIEW

File: Example/Example/EditorDemoController.swift [hunk 1]
```diff
@@ -1078,17 +1076,16 @@ extension EditorDemoController: TextViewAttachmentDelegate {
...
                 richTextView.refresh(selectedAttachment)
             }
 
             // and mark the newly tapped attachment
-            let message = NSLocalizedString("Options", comment: "Options to show when tapping on a media object on the post/page editor.")
-            attachment.message = NSAttributedString(string: message, attributes: mediaMessageAttributes)
-            if attachment.overlayImage == nil {
-                attachment.overlayImage = Gridicon.iconOfType(.pencil).withRenderingMode(.alwaysTemplate)
-                attachment.overlayImage = Gridicon.iconOfType(.pencil, withSize: CGSize(width: 32.0, height: 32.0)).withRenderingMode(.alwaysTemplate)
+            if (attachment.message == nil) {
```
Comment (jleandroperez) [inline Example/Example/EditorDemoController.swift]: No need for braces ` ( ) `

File: Aztec/Classes/TextKit/VideoAttachment.swift [hunk 2]
```diff
@@ -66,6 +66,21 @@ open class VideoAttachment: MediaAttachment {
...
 
+    /// An image to display overlaid on top of the media
+    ///
+    open override var overlayImage: UIImage? {
+        set(newValue) {
+            if newValue == nil {
+                super.overlayImage = Assets.playIcon
+            } else {
+                super.overlayImage = newValue
+            }
```
Comment (jleandroperez) [inline Aztec/Classes/TextKit/VideoAttachment.swift]: This one can be simplified as follows:

```
set {
    super.overlayImage = newValue ?? Assets.playIcon
}
```
