### PR TITLE
NSParagraphStyle's isEqual now compares correctly against ParagraphStyle.

### LINKED ISSUE #917: Style loss when using NSParagraphStyle objects
### Description

When using `NSParagraphStyle` we're sometimes losing styling information.

### Details

This can be checked by running `testFigcaptionGetsItsStyleProperlyParsed()` several times.  For some reason it doesn't fail every time, but when it does it's because we're losing style information from our `ParagraphStyle` objects.

It seems the culprit is that `NSParagraphStyle.isEqual()` fails to recognize the difference with `Aztec.ParagraphStyle` objects with the same base properties.

### PR DESCRIPTION
**Pull request by diegoreymendez**
### Description

Fixes #917 through method swizzling.

`NSParagraphStyle.isEqual()` now properly compares using `isEqual()` against `ParagraphStyle` objects.

Added two unit tests that trigger the problem.

### Testing

 Run the unit tests multiple times and make sure they never fail.

### CODE REVIEW

File: Aztec/Classes/TextKit/ParagraphStyle.swift [hunk 1]
```diff
@@ -419,4 +429,29 @@ extension ParagraphStyle {
...
+                return
+        }
+        
+        method_exchangeImplementations(originalMethod, swizzledMethod)
+    }
+}
+
+extension NSParagraphStyle {
+    @objc func swizzledIsEqual(_ object: Any?) -> Bool {
+        guard object_getClass(self) == object_getClass(object) else {
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/ParagraphStyle.swift]: What happens when you compare a NSParagraphStyle with a NSMutableParagraphStyle?

Comment (diegoreymendez) [reply Aztec/Classes/TextKit/ParagraphStyle.swift]: Well worst case scenario they're not considered equal (which I don't think is necessarily a bad thing).

That said, I'll try reviewing this logic for that scenario.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Ready for another look.
