### PR TITLE
Fixing Image Paste Glitch

### LINKED ISSUE #722: Pasting content with images is failing to load the images.
Pasting content with images is failing to load the images in visual mode.

No content is lost, though.  This is just a refreshing issue.

Steps to repro:

1. Launch the editor with sample content.
2. Copy all the sample content.
3. Go to the empty editor.
4. Paste the copied sample content.

Expected behavior: the pasted images should load.
Actual behavior: they don't load.

Props to @jleandroperez

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're:

- Preserving the UIImage scale upon un-archival
- Not overriding a MediaAttachment's **image** with a placeholder, unless we've got an actual URL to request.

Fixes #722

### To test:
1. Launch the editor with sample content.
2. Copy all the sample content.
3. Go to the empty editor.
4. Paste the copied sample content.

Verify that the pasted images do load.

### CODE REVIEW

File: Aztec/Classes/TextKit/MediaAttachment.swift [hunk 1]
```diff
@@ -334,8 +334,9 @@ private extension MediaAttachment {
     /// Requests a new asset (asynchronously), and on completion, triggers a relayout cycle.
     ///
     private func updateImage(in textContainer: NSTextContainer?) {
-
-        self.image = delegate!.mediaAttachmentPlaceholderImageFor(attachment: self)
+        if mustDisplayPlaceholder {
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/MediaAttachment.swift]: Why not avoid the method and the conditional block completely and just use the guard below to display the placeholder?

The execution path when `url == nil` in this method is a bit weird.

**Comment by jleandroperez** [comment]
@diegoreymendez apologies about over complicating things in this one. All we needed to do is to move the guard up there, not sure why i didn't see that at glance!.

Ready for another look!

**Comment by diegoreymendez** [comment]
@jleandroperez - The images are not loading unless I switch to HTML and back.  Is that a known issue?

**Comment by jleandroperez** [comment]
@diegoreymendez i've found an incredible "Initializer's Loop", in which `ImageAttachment`'s URL was getting reset.

[Fixed via this commit](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/775/commits/0821f77b14f8a796a5d5d2f87593cc4cd5dad602). Mind re-testing?. My steps are as follows:

1. Turn off Wifi
2. Launch Aztec Demo (w/content)
3. Copy all the things
4. Hit back
5. Open the Empty Document screen
6. Toggle Wifi back on
7. Paste

As a result, Bambi should show up shortly.

Thanks in advance!

File: Aztec/Classes/TextKit/MediaAttachment.swift [hunk 2]
```diff
@@ -32,7 +32,7 @@ open class MediaAttachment: NSTextAttachment {
 
     /// Identifier used to match this attachment with a custom UIView subclass
     ///
-    private(set) open var identifier: String
+    open var identifier = String()
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/MediaAttachment.swift]: This is only used by this class... and there's no public method offering any interaction with it whatsoever...

Why the change?

Comment (jleandroperez) [reply Aztec/Classes/TextKit/MediaAttachment.swift]: Because i've been dealing with the idea of switching this to a `let` constant, ended up reverting... and forgot it was `private(set)`. Nice catch!

**Comment by jleandroperez** [comment]
Thanks sir!

**Comment by diegoreymendez** [comment]
Still approved.
