### PR TITLE
Fix: Missing Cursor after Inserting Blockquote

### LINKED ISSUE #440: Blockquote: Missing Cursor
### Steps:
1. Toggle Blockquote

As a result, the cursor will be invisible (since it'll be displayed below the blockquote's background).

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #440

### To test:
1. Launch the empty editor
2. Insert a Blockquote
3. Verify that the Cursor is visible

cc @diegoreymendez 
Thanks in advance!

### CODE REVIEW

File: Aztec/Classes/TextKit/TextView.swift [hunk 1]
```diff
@@ -887,9 +887,13 @@ open class TextView: UITextView {
         let delay = 0.05
         DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
             let pristine = self.selectedRange
-            let updated = NSMakeRange(max(pristine.location - 1, 0), 0)
+            var location = max(pristine.location - 1, 0)
+            if pristine.location == location {
+                location = min(pristine.location + 1, self.storage.length)
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextView.swift]: Can we document this method, and anything that's not ovbious in it a bit more?

I'm realizing that reviewing this PR is difficult because it's not immediately obvious what the logic is.

**Comment by jleandroperez** [comment]
@diegoreymendez comment added, ready for another look!

File: Aztec/Classes/TextKit/TextView.swift (hunk 1 above)
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextView.swift]: The method documentation is appreciated, however the reasoning behind the logic in this method is still not easy to understand:

1. Why are we moving location to `-1`?
2. What's the logical meaning of `pristine.location == location`?  Can we store that in a boolean with a more meaningful name?  (for example: `selectedRangeStartsAtPositionZero`, which is what I believe we're checking for)
3. Why are we moving the location forward if `pristine.location == location`?  This is really not clear to me.

Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextView.swift]: Also, `pristine` should be stored before the block is executed, otherwise you risk using an outdated selection range.

Comment (jleandroperez) [inline Aztec/Classes/TextKit/TextView.swift]: Ahhhhh i see! Goal there is to move the **selectedRange.location** to +1 or -1, in order to force the cursor to redraw. Logic is as follows:

If we're at the end of the document... we can't move +1, or we'd trigger an Out of Bounds exception, in which case we'll proceed with -1.

(After seeing this logic a couple days later, i think it can be just simplified). Will be updating + documenting why, thanks Diego!

Comment (jleandroperez) [inline Aztec/Classes/TextKit/TextView.swift]: Actually, nope. We're storing `pristine` during the block execution **on purpose**. Reasoning behind that is:

- There's a distant, very remote chance in which the selectedRange changes between the block scheduling and acutal execution
- If the selectedRange does change, though remote, you'll see the cursor jumping around

The goal of this hack (it's indeed a **hack**) is to force TextKit to redraw the cursor, while retaining the exact position it had at the moment of execution. Initial cursor position is irrelevant, in this particular scenario.

Thanks for the feedback Diego!

**Comment by jleandroperez** [comment]
@diegoreymendez it should (hopefully) be crystal clear now. However, i'd like to note: i'm not happy with this hack, since day one. That's why we have #417 in place, perhaps there's a more suitable alternative.

Thanks Diego!!

**Comment by jleandroperez** [comment]
Thanks Diego!!
