### PR TITLE
UIPasteboard: NSCoding conformance for Aztec Attributes

### LINKED ISSUE #626: Crash: NSKeyedArchiver _encodeArrayOfObjects
```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x181a19014 __pthread_kill + 8
1  libsystem_pthread.dylib        0x181ae3264 pthread_kill + 112
2  libsystem_c.dylib              0x18198d9c4 abort + 140
3  libswiftCore.dylib             0x10186fd14 swift::fatalError(unsigned int, char const*, ...) + 54
4  libswiftCore.dylib             0x10187e00c -[SwiftObject doesNotRecognizeSelector:] + 94
5  CoreFoundation                 0x182a22f54 ___forwarding___ + 916
6  CoreFoundation                 0x18291ed4c _CF_forwarding_prep_0 + 92
7  Foundation                     0x183471bbc _encodeObject + 192
8  Foundation                     0x1834733b4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 440
9  Foundation                     0x183472fe8 -[NSDictionary(NSDictionary) encodeWithCoder:] + 912
10 Foundation                     0x183471f94 _encodeObject + 1176
11 Foundation                     0x1834733b4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 440
12 Foundation                     0x183471f94 _encodeObject + 1176
13 Foundation                     0x18347e36c -[NSAttributedString encodeWithCoder:] + 1056
14 Foundation                     0x183471f94 _encodeObject + 1176
15 Foundation                     0x183478e5c +[NSKeyedArchiver archivedDataWithRootObject:] + 168
16 Aztec                          0x100eb0128 @objc NSAttributedString.archivedData() -> Data (NSAttributedString+Archive.swift:10)
17 Aztec                          0x100eec410 TextView.cut(Any?) -> () + 156
18 Aztec                          0x100eec588 @objc TextView.cut(Any?) -> () + 104
19 UIKit                          0x189158a88 -[UICalloutBar buttonPressed:] + 416
20 UIKit                          0x189157dec -[UICalloutBarButton fadeAndSendAction] + 84
21 Foundation                     0x1834fbc0c __NSFireDelayedPerform + 408
22 CoreFoundation                 0x1829cdaa4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
23 CoreFoundation                 0x1829cd7a8 __CFRunLoopDoTimer + 856
24 CoreFoundation                 0x1829cd068 __CFRunLoopDoTimers + 244
25 CoreFoundation                 0x1829cac8c __CFRunLoopRun + 1484
26 CoreFoundation                 0x1828fada4 CFRunLoopRunSpecific + 424
27 GraphicsServices               0x184364074 GSEventRunModal + 100
28 UIKit                          0x188bae058 UIApplicationMain + 208
29 WordPress                      0x1000c4ec4 main (main.m:11)
30 libdyld.dylib                  0x18190959c start + 4
```

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
- Neutralizes PR #627 (Band Aid Fix)
- Implements NSCoding conformance in a few classes: **HTMLRepresentation** + **HTMLElementRepresentation** + **UnsupportedHTML** + **Attribute**
- Serialization capabilities for **Value** + **CSSProperty**
- Nukes **MarkerNode** (dead class!)

Fixes #626

### To test:
- Verify that the unit tests are green
- Try copy / cut + paste of literally anything!

cc @diegoreymendez @SergioEstevao 

Thanks in advance gentlemen!!

### CODE REVIEW

File: Aztec/Classes/NSAttributedString/HTML/HTMLRepresentation.swift [hunk 1]
```diff
@@ -2,13 +2,67 @@ import Foundation
...
 /// This enum specifies the different entities that can represent a style in HTML.
 ///
-enum HTMLRepresentation {
-    case attribute(Attribute)
-    case element(HTMLElementRepresentation)
-    case inlineCss(CSSProperty)
+class HTMLRepresentation: NSObject {
+    enum Kind {
+        case attribute(Attribute)
+        case element(HTMLElementRepresentation)
```
Comment (SergioEstevao) [inline Aztec/Classes/NSAttributedString/HTML/HTMLRepresentation.swift]: How about renaming HTMLElementRepresentation to HTMLElement or Element to match the other cases?

**Comment by jleandroperez** [comment]
Thanks a lot for the review @SergioEstevao !!!
