### PR TITLE
Issue/1086 blockquote multilevel support

### LINKED ISSUE #1086: Nested blockquote style
Hello to all, thank for awesome library. I use it for displaying static html text, by using isEditable=false.
I try to display nested blockqutotes, with same style as parent one.
### Expected behavior
Expected behavior: nested blockquotes has the same style as parent one: at least left border line.

<blockquote><blockquote>многострочная цитатка<blockquote>теперь оч сложный вариант<br />сначала тут текст у нас<br />потом внизу цитата</blockquote><br /><div><br /></blockquote><br />вло<br /><br /></blockquote>

### Actual behavior
Nested quotes display as usual text, but with tab.
screen shot 2018-11-18 at 5 31 34 pm

### Steps to reproduce the behavior
Create nested blockquote text. For example:
<blockquote>hi test<blockquote>nested one</blockquote></blockquote>

##### Tested on [device], iOS [version], Aztec [version]
Tested on iOS Simulator iPhone XR
iOS 12.1
Aztec version 1.1

### PR DESCRIPTION
**Pull request by MadeByDouglas**
Fixes #1086 

To test: new array method of tracking nested colors and next / previous index logic cleaned up to be more readable

replaces PR #1252 

**Original PR Description**

To test: try tabbing and shift tabbing to go through nested quotes

**Features:**

supports up to 9 levels of indentation, arbitrary, could be more, but seemed enough
supports from 1 to 5 levels of colored quotes, editable by user of the API, default is 5
style can be made to look like apple mail app or other mail apps by removing background color and customizing colors

Screen Shot 2019-12-09 at 7 56 50 PM

**Known issue:**
when pasting quotes from either internally or externally such as a mail client, the text color doesn't change properly. Something with the tryPastingHTML method and replace not correctly getting color for new string. Would appreciate help fixing this.

### CODE REVIEW

File: Aztec/Classes/TextKit/LayoutManager.swift [hunk 1]
```diff
@@ -8,8 +8,13 @@ import QuartzCore
 class LayoutManager: NSLayoutManager {
 
     /// Blockquote's Left Border Color
-    ///
-    var blockquoteBorderColor: UIColor? = UIColor(red: 0.52, green: 0.65, blue: 0.73, alpha: 1.0)
+    /// Include 3 nested values
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/LayoutManager.swift]: This comment is outdated, probably should indicate what is the purpose of the variable and don't mention the number of levels that can be changed depending of the needs.

File: Aztec/Classes/TextKit/LayoutManager.swift [hunk 2]
```diff
@@ -73,6 +78,19 @@ private extension LayoutManager {
...
+                guard nestDepth >= 1 else {return}
+                for index in 1...nestDepth {
+                    let indent = CGFloat(index) * Metrics.listTextIndentation
+                    
+                    let nestRect = self.blockquoteRect(origin: origin, lineRect: rect, blockquoteIndent: indent, lineEndsParagraph: lineEndsParagraph)
+                    
+                    self.drawNestedBlockquote(in: nestRect.integral, with: context, at: index)
+                }
+                
+
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/LayoutManager.swift]: Instead of having this two different ways of drawing the borders I suggest we do the following changes:

 - Rename the method `drawBlockquote()` to be `drawBlockquoteBackground()` and change it to only draw the background of the blockquote.
 - Rename the `drawNestedBlockquote()` to be `drawBlockquoteBorder()` and use it to draw **all** the borders of the blockquote.

This will simplify the code and it make more obvious the steps involved.

File: Aztec/Classes/TextKit/TextView.swift [hunk 3]
```diff
@@ -223,6 +223,12 @@ open class TextView: UITextView {
     // MARK: - Properties: Text Lists
 
     var maximumListIndentationLevels = 7
+    
+    // MARK: - Properties: Blockquotes
+    
+    /// The max levels of quote indentation allowed
+    /// Set to 9 for iPhone sized screen, 24 for other devices
+    var maximumBlockquoteIndentationLevels = UIDevice.current.userInterfaceIdiom == .phone ? 9 : 24
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/TextView.swift]: I think it's better to have a single value here and let users of the library change it according to their needs. 

Also on the iPad we have to support the multitask modes where the screen can have the same width of a phone and 24 levels don't make sense then.

File: Aztec/Classes/TextKit/TextView.swift [hunk 4]
```diff
@@ -983,7 +1095,21 @@ open class TextView: UITextView {
...
+        //get original color or previous nested color as appropriate when toggling back and forth
+        var originalQuoteAttributes = typingAttributes
+        originalQuoteAttributes.removeValue(forKey: .foregroundColor)
+        
+        let textColor = getTextColorForQuoteDepth(currentDepth, toggle: true)
+        originalQuoteAttributes[.foregroundColor] = textColor.prev
+        
+        let formatter = BlockquoteFormatter(placeholderAttributes: originalQuoteAttributes)
+        //use the first color when toggling on
+        formatter.nextTextColor = textColor.next
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/TextView.swift]: At the moment I don't think we should change the color of the text in the blockquote. I understand that you have a need for this for your work, but can we handle this in a separate follow up PR?

The color changes need to be done inside the formatter and we will need to send the value of color to apply/revert to the formatter, but again I think that change should be done on a separate PR and we should focus on the border color on this one.

File: Aztec/Classes/TextKit/LayoutManager.swift [hunk 5]
```diff
@@ -122,6 +140,20 @@ private extension LayoutManager {
 
         return blockquoteRect
     }
+    
+    private func drawNestedBlockquote(in rect: CGRect, with context: CGContext, at depth: Int) {
+        
+        let quoteCount = blockquoteBorderColors.count
+        let index = depth < quoteCount ? depth : quoteCount-1
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/LayoutManager.swift]: I think this will be easier to write like this: ```min(depth, quoteCount-1)```

File: Aztec/Classes/TextKit/LayoutManager.swift (hunk 2 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: oh good idea

File: Aztec/Classes/TextKit/TextView.swift (hunk 3 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/TextView.swift]: hmm, true I wasn't sure how to do the compact width check here. Also if user can change this and it happens to be less than whats in the `blockquoteBorderColors` array it will crash. I think I will just make this value be the count of `blockquoteBorderColors` +9, that should cover any reasonable use case, and on compact widths with high indent, it will just look a little funny, but thats unlikely to happen anyway

Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/TextView.swift]: ok, that makes sense. I will just make it public var then.

Yeah, I wasn't sure how to get compactWidth in that instance didnt spend too much time on it

File: Aztec/Classes/TextKit/TextView.swift (hunk 4 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/TextView.swift]: ok, I will separate that out into another PR

File: Aztec/Classes/TextKit/LayoutManager.swift (hunk 5 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: oh yes much better 😅

File: Aztec/Classes/TextKit/LayoutManager.swift [hunk 6]
```diff
@@ -72,7 +76,22 @@ private extension LayoutManager {
...
+                //nested blockquote
+                let nestDepth = paragraphStyle.blockquoteNestedIndent.depth
+                guard nestDepth >= 1 else {return}
+                for index in 1...nestDepth {
+                    let indent = CGFloat(index) * Metrics.listTextIndentation
+                    
+                    let nestRect = self.blockquoteRect(origin: origin, lineRect: rect, blockquoteIndent: indent, lineEndsParagraph: lineEndsParagraph)
+                    
+                    self.drawBlockquoteBorder(in: nestRect.integral, with: context, at: index)
+                }
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/LayoutManager.swift]: We could merge the drawing of the border 0 and other depths by just doing this: 
```
               let nestDepth = paragraphStyle.blockquoteNestedIndent.depth               
                for index in 0...nestDepth {
                    let indent = CGFloat(index) * Metrics.listTextIndentation

                    let nestRect = self.blockquoteRect(origin: origin, lineRect: rect, blockquoteIndent: indent, lineEndsParagraph: lineEndsParagraph)

                    self.drawBlockquoteBorder(in: nestRect.integral, with: context, at: index)
                }
```

File: Aztec/Classes/TextKit/LayoutManager.swift [hunk 7]
```diff
@@ -122,20 +142,27 @@ private extension LayoutManager {
 
         return blockquoteRect
     }
+    
+    private func drawBlockquoteBorder(in rect: CGRect, with context: CGContext, at depth: Int) {
+        
+        let quoteCount = blockquoteBorderColors.count
+        let index = min(depth, quoteCount-1)
+        
+        if blockquoteBorderColors.indices.contains(index) {
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/LayoutManager.swift]: this could be rewritten like this:
```
guard index < blockquoteBorderColors.count else {
  return
}
```

File: Aztec/Classes/TextKit/LayoutManager.swift (hunk 6 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: hmm yep!

File: Aztec/Classes/TextKit/LayoutManager.swift (hunk 7 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: thats true, I guess is that more performant than `indices.contains` also? (although its a small array)

I was trying to keep similar style to the `func drawBlockquoteBackground` on line 158 which uses an `if let`.

but I guess it doesn't really matter and actually I think a guard makes more sense for both.

File: Aztec/Classes/TextKit/ParagraphStyle.swift [hunk 8]
```diff
@@ -191,6 +191,23 @@ open class ParagraphStyle: NSMutableParagraphStyle, CustomReflectable {
...
+        var depth = 0
+        for position in (0..<listAndBlockquotes.count).reversed() {
+            if listAndBlockquotes[position] is Blockquote {
+                depth = position
+                break
+            }
+        }
+        let indent = CGFloat(depth) * Metrics.listTextIndentation
+        return (depth, indent)
+    }
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/ParagraphStyle.swift]: Can we please split this in two methods, one to calculate  the depth and another for the indent value?

The one for indent can use the method for depth inside.

Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/ParagraphStyle.swift]: yeah, I was just following the established pattern for these vars as they were used for the list and thought a tuple was an elegant solution to get the depth info, but I can split it up. Actually it reminds me I need to merge it with the `blockquoteIndent` var right above it

Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/ParagraphStyle.swift]: ok interesting, when I have only `blockquoteIndent` var rather than both that and `blockquoteNestedIndent` then the background rect shifts as you can see here. I guess I will keep both vars to keep original behavior. 
Screen Shot 2019-12-16 at 5 13 53 PM

Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/ParagraphStyle.swift]: well you can see the solution I came up with; just one var, but the block quote background always starts at indent of 0

**Comment by SergioEstevao** [comment]
It looks we have a small bug when we have blockquotes inside lists, look at the screenshot bellow from the Standard Demo content:

Screenshot 2019-12-18 at 22 23 22

**Comment by MadeByDouglas** [comment]
oh interesting. I guess its because they share how they indent lists? Which you need so the spacing is correct, but somehow block quote inside a list needs to know to push the content over further from left and yet still start depth at its own count. Hmm.
```
public var blockquoteDepth: Int {
        let listAndBlockquotes = properties.filter({ property in
            return property is Blockquote || property is TextList
        })
        var depth = 0
        for position in (0..<listAndBlockquotes.count).reversed() {
            if listAndBlockquotes[position] is Blockquote {
                depth = position
                break
            }
        }
        return depth
    }

    /// The amount of indent for the list of the paragraph if any.
    ///
    public var listIndent: CGFloat {
        let listAndBlockquotes = properties.filter({ property in
            return property is Blockquote || property is TextList
        })
        var depth = 0
        for position in (0..<listAndBlockquotes.count).reversed() {
            if listAndBlockquotes[position] is TextList {
                depth = position
                break
            }
        }

        return CGFloat(depth) * Metrics.listTextIndentation
    }
```

**Comment by MadeByDouglas** [comment]
should be fixed, check the standard demo now

File: Aztec/Classes/TextKit/LayoutManager.swift [hunk 9]
```diff
@@ -8,8 +8,12 @@ import QuartzCore
 class LayoutManager: NSLayoutManager {
 
     /// Blockquote's Left Border Color
-    ///
-    var blockquoteBorderColor: UIColor? = UIColor(red: 0.52, green: 0.65, blue: 0.73, alpha: 1.0)
+    /// Set the array with how many colors you like, they appear in the order they are set in the array.
+    var blockquoteBorderColors = [UIColor(hexString: "9252FF")!,
```
Comment (SergioEstevao) [inline Aztec/Classes/TextKit/LayoutManager.swift]: As a default I would like to have just a single color like this: `[UIColor.gray]` then users of the library can configure to their needs.

File: Example/Example/EditorDemoController.swift [hunk 10]
```diff
@@ -181,7 +181,7 @@ class EditorDemoController: UIViewController {
             editorView.richTextView.textColor = UIColor.label
             editorView.richTextView.blockquoteBackgroundColor = UIColor.secondarySystemBackground
             editorView.richTextView.preBackgroundColor = UIColor.secondarySystemBackground
-            editorView.richTextView.blockquoteBorderColor = UIColor.secondarySystemFill
+            editorView.richTextView.blockquoteBorderColors = [.red, .blue, .green]
```
Comment (SergioEstevao) [inline Example/Example/EditorDemoController.swift]: To keep the demo consistent with what we have before can we put the `UIColor.secondarySystemFill` as the first color on the array, and then for other colors use the system version to adapt to the dark/light modes.
So it should be something like this in the end:
```
[UIColor.secondarySystemFill, UIColor.systemRed, UIColor.systemBlue, UIColor.systemGreen]
```

File: Aztec/Classes/TextKit/LayoutManager.swift (hunk 9 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: oh, I had picked such a nice default color theme though. But yeah, I guess that makes sense

Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: should I use `systemGray` instead of `gray` ?

Comment (SergioEstevao) [reply Aztec/Classes/TextKit/LayoutManager.swift]: At this location because the library still supports iOS11 we should stick to gray that is available on all version of the OS since iOS11.

If you use systemGray then you need to put code to branch it depending of building to iOS 13 or a previous version of the OS.

File: Example/Example/EditorDemoController.swift (hunk 10 above)
Comment (MadeByDouglas) [reply Example/Example/EditorDemoController.swift]: OK I dropped the red because it contrasts a lot and just use teal and blue which go with the gray better I think for default theme

File: Aztec/Classes/TextKit/LayoutManager.swift (hunk 9 above)
Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: well I thought that but it seems system gray works on older iOS releases, it let me put it without saying had to be iOS 13.

also here it says since iOS 7.0, but documentation says that for all system colors which doesn't make sense https://developer.apple.com/documentation/uikit/uicolor/3173143-systemgray

Comment (MadeByDouglas) [reply Aztec/Classes/TextKit/LayoutManager.swift]: it seems that semantic colors like `systemBackground` require iOS 13 where as the other system colors like `systemRed` or `systemGray` have a fallback / or have been around that allows them to be used since iOS 7, although it depends, `systemIndigo` requires iOS 13 and `systemPurple` iOS 9 etc.
Screen Shot 2020-01-07 at 4 02 44 PM

**Comment by SergioEstevao** [comment]
I just pushed a small update to fix a scenario where the border color array was emtpy.
All looking good now!

**Comment by MadeByDouglas** [comment]
awesome! thanks for the small fix
