### PR TITLE
Make Gutenberg blocks mergeable

### LINKED ISSUE #977: Gutenberg blocks are being split when they contain more than one block element
### Expected behavior

This HTML:
```
<!-- wp:list -->
<ul>
    <li>Media library/HTML for images, multimedia and approved files.</li>
    <li>Pasted links for embeds.</li>
    <li>Shortcodes for specialized assets from plugins.</li>
    <li>Featured images for the image at the top of a post or page.</li>
    <li>Excerpts for subheads.</li>
    <li>Widgets for content on the side of a page.</li>
</ul>
<!-- /wp:list -->
```

Should be maintained after opening it on Aztec

### Actual behavior

The end content that is produced is the following:
```
<!-- wp:list -->
<ul>
  <li>Media library/HTML for images, multimedia and approved files.</li>
</ul>
<!-- /wp:list -->
<!-- wp:list -->
<ul>
  <li>Pasted links for embeds.</li>
</ul>
<!-- /wp:list -->
<!-- wp:list -->
<ul>
  <li>Shortcodes for specialized assets from plugins.</li>
</ul>
<!-- /wp:list -->
<!-- wp:list -->
<ul>
  <li>Featured images for the image at the top of a post or page.</li>
</ul>
<!-- /wp:list -->
<!-- wp:list -->
<ul>
  <li>Excerpts for subheads.</li>
</ul>
<!-- /wp:list -->
<!-- wp:list -->
<ul>
  <li>Widgets for content on the side of a page.</li>
</ul>
<!-- /wp:list -->
```

### Steps to reproduce the behavior

- Start the Gutenberg demo
- Switch to HTML mode
- Copy paste the sample HTML on the expected section above
 - Switch to Visual and the back to HTML
 - See the resulting HTML

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #977 

This PR makes the following changes:
 - Make the definition of mergeable elements configurable from the outside of the library
 - Add Gutenblocks to the list of mergeable blocks
 - Add a special rule for Gutenblocks merge where this can only happen when they have elements that are mergeable them selfs.

To test:
 - Run unit tests to make sure all are green.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@diegoreymendez this is starting to look better but I found to tests that are failing that I'm not 100% sure why, do you mind to have a look and see if you find anything that I'm missing.

File: Aztec/Classes/Libxml2/DOM/Data/Element.swift [hunk 1]
```diff
@@ -13,14 +13,25 @@ public struct Element: RawRepresentable, Hashable {
...
     /// List of void elements.  These will *not* to have a closing tag and cannot have children.
     ///
     /// Ref. http://w3c.github.io/html/syntax.html#void-elements
     ///
     public static var voidElements: [Element] = [.area, .base, .br, .col, .embed, .hr, .img, .input, .link, .meta, .param, .source, .track, .wbr]
-    
+
+    /// List of block HTML elements that can be merged together when they are sibling to each other
+    ///
+    public static var mergeableBlocklevelElements: Set<Element> = Set([.blockquote, .div, .figure, .figcaption, .h1, .h2, .h3, .h4, .h5, .h6, .hr, .li, .ol, .ul])
```
Comment (diegoreymendez) [inline Aztec/Classes/Libxml2/DOM/Data/Element.swift]: Capitalize the `L` in `level`.

File: WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift [hunk 2]
```diff
@@ -103,8 +107,12 @@ private extension GutenbergInputHTMLTreeProcessor {
     func openerAttributes(for commentNode: CommentNode) -> [Attribute] {
         let attributeName = GutenbergAttributeNames.blockOpener
         let openerBase64String = encode(commentNode)
-        
-        return [Attribute(name: attributeName, value: .string(openerBase64String))]
+        // TODO: Parse and create an extra attribute to get the block name.
```
Comment (diegoreymendez) [inline WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift]: I think we should roll back these changes, unless there's a reason to do the extra name processing.

File: WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeNames.swift [hunk 3]
```diff
@@ -8,4 +8,5 @@ struct GutenbergAttributeNames {
     public static let selfCloser = "selfCloser"
     public static let blockOpener = "opener"
     public static let blockCloser = "closer"
+    public static let blockType = "blockType"
```
Comment (diegoreymendez) [inline WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeNames.swift]: I think this probably needs to be rolled back too.

File: Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift [hunk 4]
```diff
@@ -282,12 +279,27 @@ public class ElementNode: Node {
...
-        return ElementNode.mergeableBlocklevelElements.contains(type)
+        return isBlockLevelMergeable()
     }
 
+    public func isBlockLevelMergeable() -> Bool {
+        guard Element.mergeableBlockLevelElements.contains(type) else {
+            return false
+        }
+        guard Element.mergeableBlocklevelElementsSingleChildren.contains(type) else {
+            return Element.mergeableBlockLevelElements.contains(type)
```
Comment (diegoreymendez) [inline Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift]: At this point this should be `return true`.

**Comment by diegoreymendez** [comment]
So I just found something extremely confusing.

If you add a breakpoint [here](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/issue/977_mergeable_gutenberg_blocks/Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift#L353) and do:

`po leftMerger`
`po rightMerger`

You'll notice that the merge should actually be succeeding.

To validate this theory just do:

`po leftMerger.children += rightMerger.children`

and continue execution, and you'll notice the test succeeds.

**Comment by SergioEstevao** [comment]
@diegoreymendez thanks for the last fix! This is looking good!
