### PR TITLE
Fixes a bug that was causing paragraphs to merge.

### LINKED ISSUE #1005: Paragraphs are being merged when they shouldn't.
Paragraphs are being merged when they shouldn't.

paragraphsmerged

### PR DESCRIPTION
**Pull request by diegoreymendez**
### Description:

Fixes a bug that was causing paragraphs to merge when they shouldn't.

Fixes #1005 

This is what the original issue looked like:

paragraphsmerged

### Details:

- [Added unit tests](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-40513c251786f2880b02c4f1f38730f3R40) that can automatically detect this issue if it ever arised again.
- [Reorganizes the code a bit](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-8f0997fe69197252915ff1a894213dfdR6) since to fix this issue I have to reuse some of the code we already have from [a new location](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-48ee906bc2164480c9dfa48c13d0f995R6).
- Also fixes a bug with [how we were handling unicode characters](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-56b82478ff0ea96a9b99d6498f29ff37R18).  This issue surfaced in one of our new unit tests.
- [Changes the expectations of a unit test](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-40513c251786f2880b02c4f1f38730f3R180).  Unfortunately it seemed to be working fine previously due to the bug we had, but once the bug was fixed, a problem with non-closed Gutenberg delimiters surfaced.  I expect it to be minor.

### Testing:

Run the unit tests.

Also:
- Create a new empty Gutenberg / Calypso post in the demo app.
- Type different paragraphs of text in visual mode.
- Switch to HTML and back and make sure the text is not merged into a single paragraph.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
This PR will fix https://github.com/wordpress-mobile/WordPress-iOS/issues/9706 for Wordpress.

File: Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift [hunk 1]
```diff
@@ -105,6 +105,12 @@ public class ElementNode: Node {
     }
 
     // MARK: - Node Queries
+    
+    public func attribute(named name: String) -> Attribute? {
+        return attributes.first { (attribute) -> Bool in
```
Comment (jleandroperez) [inline Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift]: No need to change anything. I'm just annoying: `(attribute) -> Bool in`, in this case, can be compressed to just `attribute in` (because the return type gets inferred)

File: WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeEncoder.swift [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    private func attribute(_ attribute: GutenbergAttribute, withValue text: String) -> Attribute {
+        let base64String = encode(text)
+        
+        return Attribute(name: attribute, value: .string(base64String))
+    }
+    
+    // MARK: - Base64 Encoding
+    
+    private func encode(_ string: String) -> String {
+        let data = string.data(using: .utf16)!
```
Comment (jleandroperez) [inline WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeEncoder.swift]: The force unwrap creeps me out. I know it shouldn't usually fail... but we may wanna consider replacing that with a guard?

Comment (diegoreymendez) [reply WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeEncoder.swift]: As discussed privately:

- There seems to be no way to handle this without ignoring the error.
- We're not sure if there's any condition that can make this fail, or what condition that is.
- This code has only been moved.  It has been in production for a while and is not breaking.

So I'm moving ahead as it is.

**Comment by nellofn** [comment]
Just a heads up that users are still reporting this issue in iOS version 10.3.1:

1265474-zen
1266666-zen
1267186-zen
1267119-zen
1266984-zen
1266764-zen

I let them know to keep an eye on a future app release, and will reach out to them all once there's an update on this.

**Comment by diegoreymendez** [comment]
Thanks for the info @nellofn.

You should probably add these to [the issue in the WPiOS repo](https://github.com/wordpress-mobile/WordPress-iOS/issues/9706) for consistency since that's where we'd normally have the history.

**Comment by nellofn** [comment]
Good to know @diegoreymendez. I saw the issue as closed, so that's why I added it here.
